apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: blog-frontend
    spec:
      containers:
        - name: frontend
          image: 196253396965.dkr.ecr.ap-south-1.amazonaws.com/blog-frontend:tag1
          ports:
            - containerPort: 8080
          env:
            - name: BACKEND_HOST
              value: blog-backend-service
            - name: BACKEND_PORT
              value: "5000"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
